### ISSUE TITLE
Make it possible to restart the service from the log window.

### ISSUE THREAD

**Issue by Fuco1** [rejeep/prodigy.el#107]
Right now the restart process is kind of annoying.

- I am looking at the log for the service
- I have to leave it to the status buffer
- I restart, but this kills the buffer
- I have to open the log buffer again by hitting `$`.

It should be possible to restart the service from the log window.  However, it should probably not happen with just `r` or it should ask `yes-or-no-p` so that we don't kill the service by accident.

**Comment by rejeep** [comment]
Perhaps there could be a prefix key that enables all commands in the log buffer?

**Comment by Fuco1** [comment]
Good idea.  I'll look into it.
