### ISSUE TITLE
sudo issues

### ISSUE THREAD

**Issue by seanfarley** [rejeep/prodigy.el#111]
I just tried out the new `:sudo` parameter and ran into a few bugs:

1. since the process is spawned with sudo the usual `(signal-process ...)` won't be able to kill it without also gaining elevated permissions

1. for commands that are in the sudoers file with `NOPASSWD`, prodigy will still prompt for a password and accidentally send that password to the spawned process as input

~~It seems to me that setting `:cwd "/sudo::/"` is enough? That will use tramp and not interfere with (2) and will also correctly kill the process which solves (1). Thoughts?~~ I incorrectly tested `:cwd`, so  I don't have a solution yet :-(

**Comment by ecraven** [comment]
I've run into 1. (not being able to kill those processes). Could you not just run `sudo kill ...`?

**Comment by seanfarley** [comment]
Yes, but that requires another prompt to the user. In the case above, I added those command to `NOPASSWD` and I don't think `kill` should be in the `NOPASSWD` field because it's a bit to dangerous.

**Comment by ecraven** [comment]
Ah, sorry, that should have been obvious.
I've now created a systemd unit to do this. Is there any way to use prodigy to just call `systemctl start ..` and `systemctl stop ...` instead of actually launching a program?
