### ISSUE TITLE
Extending prodigy past ongoing processes

### ISSUE THREAD

**Issue by danlamanna** [rejeep/prodigy.el#40]
i don't even know if this is remotely the direction anyone would want prodigy to go, but I'll give it a shot since it's something I personally would love to manage from within emacs with prodigys interface.

The idea is, using vagrant I often have a few virtual machines either started and running, or off at any given time. It would be great to be able to manage these from within prodigy. However, a virtualbox doesn't get destroyed by sigkill'ing an ongoing command, it requires you to run `vagrant halt`. You can also inquire whether or not it's running by running `vagrant status`.

So for example, imagine the following hypothetical (and sloppy) code:   

```
(defun vagrant-check(service output)
"Takes the service, and the output of the services check-command run from within the services cwd."
  (cond ((s-matches? "running" output)
         (prodigy-set-status service 'running))
        ((s-matches? "not created" output)
         (prodigy-set-status service 'stopped))))

(prodigy-define-service
  :name "WTP"
  :command "vagrant"
  :args '("up")
  :cwd "/home/dan/vms/wtp"
  :tags '(vagrant research)
  :check-command "vagrant status"
  :check-function 'vagrant-check
  :stop-cmd '(lambda()
               (cd "/home/dan/vms/wtp")
               (shell-command "vagrant halt")))
```

Now, the check-function wouldn't have to be run every 1 second or anything - that could be something that's run with a refresh of the prodigy buffer.

Again, prodigy seems to manage ongoing output commands very well, and this is a large step in a different direction, something that could be accomplished with it's own library, so feel free to debate whether or not this "fits" :)

**Comment by tomterl** [comment]
For the time being I use the following helper script to let prodigy manage my vagrant boxes:
```bash
#!/bin/bash

function provideInput() {
    echo "" ${READ[1]}
}
trap provideInput 1
vagrant --no-provision up
coproc read
wait ${READ_PID}
vagrant halt
```

With a config like the following

```
(prodigy-define-service
  :name "Devserver"
  :tags '(vagrant)
  :command "~/.emacs.d/bin/waiting-vagrant.sh"
  :cwd "~/Projekte/webdev"
  :ready-message "Devserver started" 
  )
```

With `  config.vm.post_up_message = "Devserver started"` added to the Vagrantfile. This is a kludge until a better way is available, but if you abstain from meddling with the box outside of emacs, it works.
