### ISSUE TITLE
:init-async

### ISSUE THREAD

**Issue by humanitiesNerd** [rejeep/prodigy.el#65]
Could anyone please clarify this :init-async thing ?

What does it expect ? In the examples I saw some lambdas calling other functions. What about these other functions ? Are they custom defined elisp functions ?

What's the use case exactly ?

Thanks

**Comment by rejeep** [comment]
It works like `:init`, only that it's async, unlike init, which is sync.

That means if you have an init, it will run the function and then directly after start the service, like this:

```
run init
start service
```

The init-async does not work like this. The function is given a callback function. When that function is called, the service will start, like this:

```
run init-async with callback
  when callback is run, start service
```

That means, if the callback function is not called, the service will never start.

**Comment by humanitiesNerd** [comment]
Ok, thanks. 

And the callback function is a generic elisp function ? Or could it be another service, a tag or some prodigy provided thing ?

**Comment by rejeep** [comment]
It's just a simple Elisp function.

**Comment by humanitiesNerd** [comment]
Thank you
