### ISSUE TITLE
View associated information with TAB

### ISSUE THREAD

**Issue by danlamanna** [rejeep/prodigy.el#75]
Similar to how magit's interface can show the file diff by using TAB in a manner which expands and retracts - would anyone else find it useful to have this type of interface within prodigy for displaying metadata associated with a service?

For example, I might have a SimpleHTTPServer running and I want to know the port and path, etc. Just as a means to display some metadata associated with a service that may or may not be multi-lined without adding columns or anything.

**Comment by rejeep** [comment]
There already is an old issue for this (see https://github.com/rejeep/prodigy.el/issues/9). But, yes, it would be nice.
