### ISSUE TITLE
Specifying process-connection-type (and thus pipe vs pty)

### ISSUE THREAD

**Issue by ianbattersby** [rejeep/prodigy.el#79]
Apologies for what may be a stupid question, I'm very new to ELISP and LISP in general but battling my way through a small project which prodigy is playing a pivotal role in its workflow. Any guidance you can give is much appreciated!

I have a process I want to start via prodigy but which needs to run with pipe and not pty, which I would normally specify with a enclosing `(let ((process-connection-type nil)) ..)`. From looking at the code I can't see specifying an synchronous `init` will do this for me, so how would I go about it?

Thanks in advance.

**Comment by rejeep** [comment]
Hey, sorry for the late reply, just had a kid, so not much extra time for hacking... :smile: 

I haven't used the `process-connection-type` variable my self before, but maybe we could add a new property `:connection-type`, like so:

```lisp
(prodigy-define-service
  :name "Name"
  :cwd "/path/to"
  :command "command"
  :args '("foo" "bar" "baz")
  :connection-type :pty
  ;; or :connection-type :pipe
  )
```

I'm not sure exactly what you're asking for, but would that solve your issue?

**Comment by ianbattersby** [comment]
Congratulations! I'm three years on and still struggling to find time :-p

I *had* thought this was the reason for an issue I was having but have since removed the hack I'd put in and it continues to work, so leave it with me and I'll re-open if it indeed a blocker for me. Thanks for your time.
