### ISSUE TITLE
Tag inheritance doesn't include port/URL?

### ISSUE THREAD

**Issue by BrianHicks** [rejeep/prodigy.el#83]
Hey there,

I have the following tag/service configuration:

```elisp
  ;; prodigy tags
  (prodigy-define-tag
    :name 'webpack-dev-server
    :command "webpack-dev-server"
    :url "http://localhost:8080")

  ;; prodigy services
  (prodigy-define-service
    :name "lingo"
    :cwd (expand-file-name "~/code/oss/lingo")
    :tags '(webpack-dev-server))
```

But it appears that `:url` in the tag is not used. When I try to open the service after running it, Prodigy says "Service does not specify url or port, cannot determine url." Am I doing something wrong with this?

**Comment by rejeep** [comment]
Thanks for reporting, can you see if this solves your issue? https://github.com/rejeep/prodigy.el/pull/84
