### ISSUE TITLE
`prodigy-start-service` doesn't add `:process-status` or `:status` which causes an error in `prodigy-stop-service`

### ISSUE THREAD

**Issue by FrancisMurillo** [rejeep/prodigy.el#85]
When I start a service with `prodigy-start-service` and stop it with `prodigy-stop-service`, I get an `Status stopping not defined`. I can work around this by calling `prodigy-define-default-status-list`. So would it be better to call said function when `prodigy-set-status` sees `prodigy-set-status-list` is nil?

By the way, great job with this.

**Comment by rejeep** [comment]
Closing via https://github.com/rejeep/prodigy.el/pull/86
