### ISSUE TITLE
[Feature] Automatically create jump to process buffer binding on defining services

### ISSUE THREAD

**Issue by FrancisMurillo** [rejeep/prodigy.el#90]
Hey dood,

When I open an Emacs projectile project I have an hook that activates a service automatically. It would be nice if prodigy creates an automatic key binding to open those buffers with ease. 

What I attempted for now is advice `prodigy-define-service` and look for `:bind` and `:bind-map` properties in the service plist and do this (more or less):

```elisp
(define-key 
  bind-map 
  bind 
  (lambda () 
    (prodigy-switch-to-process-buffer 
      service ;; Some service variable under closure
      )))
```

I also wrapped the opening function as an named command with the name from `:bind-command-name` so that it will look good for `which-key`.

**Comment by rejeep** [comment]
I don't see why prodigy should do anything like that? I can see that a projectile-prodigy.el package would be nice to easier handle services for the specific project, but not in prodigy.

Closing, but let me know if you hack up something like projectile-prodigy.el. 😄

**Comment by FrancisMurillo** [comment]
Cool, I didn't think it would be the prime directive of prodigy to make command bindings anyway. I was thinking in terms of `use-package`.

What I did so far is instead of a project, I set a default filter(tag primarily) for the prodigy buffer everytime I switch to a workgroup so that I can only see the services related to the workgroup.

**Comment by rejeep** [comment]
I see, but I guess a package like that would be quite useful. There are tons of stuff you could do to improve the "project" experience.

**Comment by FrancisMurillo** [comment]
For posterity, would you mind to describe what `projectile-prodigy` does? I might consider it a good research topic to do. Like, does it autostart services related to a project when the project is loaded? Or how does one associate a service with a project (`.dir-locals`)?

**Comment by rejeep** [comment]
> For posterity, would you mind to describe what projectile-prodigy does?

It doesn't exist! What I said was that it might be a good idea to create such a package.

**Comment by FrancisMurillo** [comment]
I just thought you might have some idea. Thanks.

**Comment by rejeep** [comment]
Nothing specific no, but things like starting/stopping all services for a project would be nice for example.
