### ISSUE TITLE
Reload prodigy services list

### ISSUE THREAD

**Issue by FrancescElies** [rejeep/prodigy.el#92]
While I'm in a emacs session I could define a new service
For example
```
(prodigy-define-service
  :name "Rails"
  :command "bundle"
  :args '("exec" "rails" "server")
  :cwd "/path/to/my/project"
  :tags '(rvm rails))
```
I evaluate this code but prodigy seems not to notice this changes until I reload emacs.
Is there a way to reload the list of defined services without having to restart emacs?

Tanks for your time

**Comment by rejeep** [comment]
You can always kill the buffer, but I think hitting `g` should be enough?

**Comment by FrancescElies** [comment]
works nicely, thanks for the tip!
