### ISSUE TITLE
Is it possible to go to first Failed process?

### ISSUE THREAD

**Issue by FrancescElies** [rejeep/prodigy.el#97]
Hi,

in case I use `prodigy-mark-tag` and start a couple of processes, if one of those failed I would like to bring the cursor directly over there. Is there something available to do that or do I need to write a custom function for that?

Thanks in advance for your time!
Best,
Francesc

**Comment by rejeep** [comment]
There is no way of doing exactly what you ask, no. But try out `prodigy-next-with-status` (`M-n`), it will move to the next service with a status. If this isn't good enough for you, the function gives you an example of how to write a function like the one you ask for, should be very easy! 😃
